name: Docker Vulnerability Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: W3D3-4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare target directory
        run: mkdir -p target

      - name: Run scan - main image
        run: |
          docker build -t my_local_image:latest .
          docker save my_local_image:latest -o target/my_local_image_latest.tar
          docker run -v $(pwd)/target:/target --rm propageur/scanner:latest \
            --archive=/target/my_local_image_latest.tar \
            --discord-webhook=${{ secrets.DISCORD_WEBHOOK_URL }} \
            --project="SCANNER FROM GITHUB ACTION"

      - name: Run scan - node
        run: |
          docker build -t node:vuln -f Dockerfile.node .
          docker save node:vuln -o target/node_vuln.tar
          docker run -v $(pwd)/target:/target --rm propageur/scanner:latest \
            --archive=/target/node_vuln.tar \
            --discord-webhook=${{ secrets.DISCORD_WEBHOOK_URL }} \
            --project="NODE FROM GITHUB ACTION"

      - name: Run scan - python
        run: |
          docker build -t python:vuln -f Dockerfile.python .
          docker save python:vuln -o target/python_vuln.tar
          docker run -v $(pwd)/target:/target --rm propageur/scanner:latest \
            --archive=/target/python_vuln.tar \
            --discord-webhook=${{ secrets.DISCORD_WEBHOOK_URL }} \
            --project="PYTHON FROM GITHUB ACTION"